# Generated by Django 4.1.7 on 2023-05-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='topic_name',
        ),
        migrations.DeleteModel(
            name='Access_Records',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
